name: Cub3D Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y make gcc xorg libxext-dev libbsd-dev

      #- name: Build project
      #  run: make

      - name: Run tests
        run: ./tests/run_tests.sh
